### ISSUE TITLE
What NTP library are you using

### ISSUE THREAD

**Issue by TropicMike** [lmirel/MorphingClockRemix#1]
I'm trying to build your code, but I keep getting:

class NTPClient' has no member named 'getHour'

What library do I need to get?  Google is showing some libs with "getHours" (with the 's') but nothing really for getHour.

**Comment by lmirel** [comment]
main code is based on the NTPClient lib example for ESP, the lib itself is used as is for NTP sync https://github.com/2dom/NtpClient
I suggest you take the lib from there as zip and add it to your sketch. it will update your libs automagically.

more info in the README or on the landing page https://github.com/lmirel/MorphingClockRemix

**Comment by TropicMike** [comment]
Thank you, Imirel.  I just noticed your reply in the comments on Harifun's page and compiled it about 30 seconds ago -- right when you were replying :)
