### ISSUE TITLE
Rainbow Effect Clock Digit

### ISSUE THREAD

**Issue by UseAfterMe** [lmirel/MorphingClockRemix#10]
I have tried with no success to change the white clock digits to any other color than what the default is in the latest branch. The default white that is set has a nasty rainbow effect when you look at the clock quickly or blink when looking at the clock.

//=== SEGMENTS ===
int cin = 25; //color intensity
#include "Digit.h"
Digit digit0(&display, 0, 63 - 1 - 9*1, 8, display.color565(0, 0, 255));
Digit digit1(&display, 0, 63 - 1 - 9*2, 8, display.color565(0, 0, 255));
Digit digit2(&display, 0, 63 - 4 - 9*3, 8, display.color565(0, 0, 255));
Digit digit3(&display, 0, 63 - 4 - 9*4, 8, display.color565(0, 0, 255));
Digit digit4(&display, 0, 63 - 7 - 9*5, 8, display.color565(0, 0, 255));
Digit digit5(&display, 0, 63 - 7 - 9*6, 8, display.color565(0, 0, 255));

But it looks like it's pulling the digit colors form somewhere else, because changing any of these values does absolutely nothing.

**Comment by lmirel** [comment]
I overwrite the colours for dimmed day/night mode:
  //reset digits color
  digit0.SetColor (cc_gry);
  digit1.SetColor (cc_gry);
  digit2.SetColor (cc_gry);
  digit3.SetColor (cc_gry);
  digit4.SetColor (cc_gry);
  digit5.SetColor (cc_gry);
  digit1.DrawColon (cc_gry);
  digit3.DrawColon (cc_gry);

**Comment by UseAfterMe** [comment]
even setting to:
  //prep screen for clock display
  display.fillScreen (0);
  int cc_blu = display.color565 (0, 0, cin);
  //reset digits color
  digit0.SetColor (cc_blu);
  digit1.SetColor (cc_blu);
  digit2.SetColor (cc_blu);
  digit3.SetColor (cc_blu);
  digit4.SetColor (cc_blu);
  digit5.SetColor (cc_blu);
  digit1.DrawColon (cc_blu);
  digit3.DrawColon (cc_blu);
  //

Does not change to blue

**Comment by UseAfterMe** [comment]
got it to work by changing line 1249 and 1250
   int cc_blu = display.color565 (0, 0, cin);
   int cc_col = cc_blu;

**Comment by lmirel** [comment]
yep, that's where they get changed for day/night mode
