### ISSUE TITLE
Unable to get into AP mode

### ISSUE THREAD

**Issue by TheLion** [lmirel/MorphingClockRemix#13]
I can't seem to get into AP mode.

With the original code from HariFun it worked fine, but with your code it doesn't.

When I press the RST button twice, the NodeMCU just resets twice and starts counting from 00-00-1970 00:00:00.

Any thoughts?

**Comment by TheLion** [comment]
Never mind. Just found out that I only cleared the sketch when uploading your code and not the rest ;-)

**Comment by lmirel** [comment]
if you don't need AP mode for configuration, you have the option of running a static configuration version.. check the 'no-wm' branch.
