### ISSUE TITLE
Clock stops morphing

### ISSUE THREAD

**Issue by TheLion** [lmirel/MorphingClockRemix#14]
Hi,

This piece of code causes the clock to stop morphing the seconds every 5 minutes at 30 seconds and jump to 37 after updating, which is combined by a flicker of the display.

```
//refresh weather every 5mins at 30sec in the minute
if (ss == 30 && ((mm % 5) == 0))
getWeather ();
}
```

Any way to fix this?

**Comment by lmirel** [comment]
unfortunately, I don't know how else to do this and also don't have a lot of time to fiddle with it.
one way to limit the impact would be to separate connectivity from response and processing but from what I've seen, the TCP connection initialisation takes the most time and the service doesn't offer keepalive (it closes connection) and I wouldn't keep the connection valid for 5min either.

if you find something that works, I'm interested.
