### ISSUE TITLE
NTPClient.cpp:13: error: 'DoubleResetDetector' does not name a type

### ISSUE THREAD

**Issue by Moko0815** [lmirel/MorphingClockRemix#17]
NTPClient.cpp:13: error: 'DoubleResetDetector' does not name a type
 DoubleResetDetector drd(DRD_TIMEOUT, DRD_ADDRESS);
 ^
sketch\NTPClient.cpp: In function 'void configModeCallback(WiFiManager*)':

NTPClient.cpp:60: error: 'drd' was not declared in this scope
   drd.stop();
   ^
sketch\NTPClient.cpp: In member function 'void NTPClient::Setup(PxMATRIX*)':

NTPClient.cpp:152: error: 'drd' was not declared in this scope

   if (drd.detectDoubleReset()) {
       ^
NTPClient.cpp:216: error: 'drd' was not declared in this scope

   drd.stop();
   ^
exit status 1
'DoubleResetDetector' does not name a type

whats wrong?

**Comment by Moko0815** [comment]
Sorry, wrong sketch...  :(


 #include <TimeLib.h>

                     ^

compilation terminated.

exit status 1
Fehler beim Kompilieren für das Board NodeMCU 1.0 (ESP-12E Module).

Which timelib is needed?

**Comment by lmirel** [comment]
Timelib is requred by https://github.com/2dom/NtpClient and is the one from https://github.com/PaulStoffregen/Time.git

Good luck and enjoy!
