### ISSUE TITLE
night mode

### ISSUE THREAD

**Issue by Frystail** [lmirel/MorphingClockRemix#19]
Hi lmirel. It says in your project description: "it has night mode from 8pm to 8am when it only shows a moon and 2 twinkling stars and a dimmed display". Is it possible to dim the screen in HariFun watches? If possible, tell me where to prescribe? Thank.
P.s. This question was asked by HariFun, he replied that it was impossible to do it now. But you did it? Please help me!

**Comment by lmirel** [comment]
there are 2 ways to 'dim' the display:
1. use the setBrightness function of the display - recommended; see https://github.com/lmirel/MorphingClockRemix/blob/no-wm/MorphingClockRemix.ino on line 1201
2. use 'dimmed' colours
in my case, I used 2. at the time I wrote it and didn't change it yet.

**Comment by Frystail** [comment]
Thanks for the answer. And how can this be transferred to the HariFun Morphing Digital Clock firmware? And then I have your firmware does not work. I can not connect to the clock by wi-fi.

**Comment by lmirel** [comment]
Someone will need to implement this feature into the original code.

If you have issues with clock configuration via WiFi, you could either use the 'no-wm' branch and configure the WiFi via parameters in the code (params.h file), or disable the icons for first time use and re-enable it after you've configured it. The WiFi manager requires more memory than it has available when the icons are in use.

**Comment by Frystail** [comment]
lmirel thanks. About the firmware from HariFun, I understood everything. The fact is that I don’t understand programming, can I learn more about params.h file and how to disable icons correctly?

**Comment by lmirel** [comment]
Checkout the 'no-wm' branch and look at the source code.
You'll have to create the params.h file yourself and add the required parameters in it, defined with your own values:

/*
 * the following parameters need to be defined in params.h
 * 
//wifi network
char wifi_ssid[] = "";
//wifi password
char wifi_pass[] = "";
//timezone
char timezone[5] = "1";
//use 24h time format
char military[3] = "Y";     // 24 hour mode? Y/N
//use metric data
char u_metric[3] = "Y";     // use metric for units? Y/N
//date format
char date_fmt[7] = "D.M.Y"; // date format: D.M.Y or M.D.Y or M.D or D.M or D/M/Y.. looking for trouble
//open weather map api key 
String apiKey   = ""; //e.g a hex string like "abcdef0123456789abcdef0123456789"
//the city you want the weather for 
String location = "Muenchen,DE"; //e.g. "Paris,FR"
 * 
 */

**Comment by Frystail** [comment]
lmirel, sorry for my ignorance. I do not know English (I use a translator), and I can not understand in any way what does the 'no-wm' branch mean? From here I don’t know how to create the params.h file.

**Comment by Frystail** [comment]
lmirel, I changed the value of 0.002 in the display_ticker.attach line (0.002, display_updater); at 0.005, I was able to connect via wi-fi and make settings. But at the same time the screen flickers very much. I haven’t figured out params.h yet. Explain how to disable and then enable icons?

**Comment by lmirel** [comment]
I've updated the 'no-wm' branch with a params.h.example file.
Download the branch from here https://github.com/lmirel/MorphingClockRemix/archive/no-wm.zip
Rename params.h.example to params.h and update it with your own values for wifi network name, password, weather.org API key if you have any, etc.

I don't know how else to help at this point but hopefully you'll manage.
