### ISSUE TITLE
request for information and other items

### ISSUE THREAD

**Issue by lmirel** [lmirel/MorphingClockRemix#2]
I am not a programmer, but was wondering if the items below can be altered.

How often does it update the weather? Is this configurable?

Is it possible to change the temp from metric to imperial?

Change date to month,day,year?

Include "Windy" or "Wind" in mph and direction? (could probably shorten the year 2018 to 18 to make some room for it).

Noticed two things: Time numbers are off center to the right.(1st digit starts at column 10 and last digit ends at column 61).

At one point, time froze for about 5-6 seconds and then started at the right time again.

(froze at 31 secs for 5-6 secs then went to 36-37 secs) just saw it once though.

Thank you for sharing.

EDIT:

Also, is it possible to configure for 12 hour time.

EDIT 2:

I noticed when logging in directly to MorphClk that the last character on each line is missing; 192.168.4 , MorphCl , etc.

This is similar to HariFun's initial code, but he corrected it due to pxmatrix was changed by the author. Are you using that version of HariFun's code?

I have 12 hour mode set but it is still showing 24 hour mode.

Finally, the shifted clock numbers to the right happen after the 1st 3 seconds of starting. Before that, it is centered. Might have to do with the pxmatrix lib.
(BOSCO)

**Comment by lmirel** [comment]
> How often does it update the weather? Is this configurable?

~line 934
`      //refresh weather every 5mins at 30sec in the minute`
`      if (ss == 30 && ((mm % 5) == 0))`
`        getWeather ();`
--many things could be configured but unfortunately, there's not a lot of room or time for it. someone could extend the wifi setup panel to add more options eventually

**Comment by lmirel** [comment]
> Is it possible to change the temp from metric to imperial?

yes, change line 317 from
`client.println("&units=metric"); `
to 
`client.println("&units=imperial"); `

then instruct the weather display function to show 'F'
line 694 from
`String lstr = String (tempM) + "C";`
to
`String lstr = String (tempM) + "F";`

**Comment by lmirel** [comment]
> Change date to month,day,year?

line 762 from
`  String lstr = (day(tnow) < 10 ? "0" + String(day(tnow)) : String(day(tnow))) + "." + 
                (month(tnow) < 10 ? "0" + String(month(tnow)) : String(month(tnow))) + "." + 
                String(year(tnow));
`
to
`  String lstr = (month(tnow) < 10 ? "0" + String(month(tnow)) : String(month(tnow))) + "." + 
                (day(tnow) < 10 ? "0" + String(day(tnow)) : String(day(tnow))) + "." + 
                String(year(tnow));
`

**Comment by lmirel** [comment]
> Include "Windy" or "Wind" in mph and direction? (could probably shorten the year 2018 to 18 to make some room for it).

this requires a bit more work, I don't think I'll do this soon, sorry

**Comment by lmirel** [comment]
> Noticed two things: Time numbers are off center to the right.(1st digit starts at column 10 and last digit ends at column 61).

on my setups they are off to the left by 1 pixel.. this is a bit too tricky to fix as it may require display-specific data

**Comment by lmirel** [comment]
> At one point, time froze for about 5-6 seconds and then started at the right time again.
(froze at 31 secs for 5-6 secs then went to 36-37 secs) just saw it once though.

unfortunately this is inevitable for now and it is due to weather data update (contacting openweathermap.org) which requires a bit of time to accomplish

**Comment by lmirel** [comment]
> Also, is it possible to configure for 12 hour time

I might have to fix it soon, sorry :-)=

**Comment by lmirel** [comment]
> I noticed when logging in directly to MorphClk that the last character on each line is missing; 192.168.4 , MorphCl , etc.
This is similar to HariFun's initial code, but he corrected it due to pxmatrix was changed by the author. Are you using that version of HariFun's code?
Finally, the shifted clock numbers to the right happen after the 1st 3 seconds of starting. Before that, it is centered. Might have to do with the pxmatrix lib.

I don't see this issue on my 2 setups and it looks like a pxmatrix lib issue.
it could be handled differently using my TinyFont library.. I might give that a try soon

**Comment by lmirel** [comment]
I fixed the 12h/24h time format issue and added the `Metric (Y/N)` configuration option to the WiFi parameter applet.

**Comment by gur001** [comment]
Hi Imirel

I am getting this error


MorphingClockRemix:843: error: 'TF_COLS' was not declared in this scope

int xo = 4*TF_COLS;

^

C:\Users\Gurjinder\Desktop\HariFun_166_Morphing_Clock-Shared\MorphingClockRemix-master\MorphingClockRemix\MorphingClockRemix.ino: In function 'void loop()':

MorphingClockRemix:902: error: 'class NTPClient' has no member named 'getHour'

hh = NTP.getHour ();

^

MorphingClockRemix:903: error: 'class NTPClient' has no member named 'getMinute'

mm = NTP.getMinute ();

^

MorphingClockRemix:904: error: 'class NTPClient' has no member named 'getSecond'

ss = NTP.getSecond ();

^

exit status 1

'TF_COLS' was not declared in this scope

**Comment by bluem6** [comment]
I've tried uploading this code but every time I do I get errors.  Would it be possible to provide a how-to instruction on uploading the code?

**Comment by Joeboyc2** [comment]
To get past these errors you need to install these library's:
NTPClient by Fabrice Weinberg
Time by Michael Margolis
NtpClientLib by Germán Martín

**Comment by gur001** [comment]
Thanks

Sent from Yahoo Mail on Android 
 
  On Sun, 19 Aug 2018 at 1:57 PM, Joeboyc2<notifications@github.com> wrote:   
To get past these errors you need to install these library's:
NTPClient by Fabrice Weinberg
Time by Michael Margolis
NtpClientLib by Germán Martín

**Comment by bluem6** [comment]
Thank you very much for the assistance.  I've install all 3 as suggested and this is the error I am currently getting: 

MorphingClockRemix:902: error: 'class NTPClient' has no member named 'getHour'

   hh = NTP.getHour ();

            ^

MorphingClockRemix:903: error: 'class NTPClient' has no member named 'getMinute'

   mm = NTP.getMinute ();

            ^

MorphingClockRemix:904: error: 'class NTPClient' has no member named 'getSecond'

   ss = NTP.getSecond ();

            ^

exit status 1
'class NTPClient' has no member named 'getHour'

**Comment by gur001** [comment]
Please send me the links for the library's
Thanks
    On Sunday, August 19, 2018, 1:57:12 p.m. PDT, Joeboyc2 <notifications@github.com> wrote:  
 
 
To get past these errors you need to install these library's:
NTPClient by Fabrice Weinberg
Time by Michael Margolis
NtpClientLib by Germán Martín

**Comment by bluem6** [comment]
I finally got it to compile.  Install only https://github.com/2dom/NtpClient and Time by Michael Margolis.  Do not install NtpClientLib by Germán Martín.  Unfortunately I have already solder up the matrix and can't test this one but was able to view it with serial monitor and it 'seems' to be working okay...
