### ISSUE TITLE
Unable to get C temp, and day from date missing

### ISSUE THREAD

**Issue by Joeboyc2** [lmirel/MorphingClockRemix#3]
Hi @lmirel,

I really like you version of the Morph clock and i have flashed my NodeMCU with it.

However, i'm having a few issues:
i only seem to be able to get the temperature to show in F and not C, i have tried to change the u_metric variable but this dosn't seem to make a difference
The date at the bottom of the clock only shows the month and year, i have checked the date_fmt and it is set to D.M.Y

Any help fixing these 2 issues would would be appreciated.

Thank you

**Comment by lmirel** [comment]
can you please activate the serial monitor and copy/paste here the output after a reset?
I'm interested to know what it reports from the 2 parameters.
thanks

**Comment by Joeboyc2** [comment]
sure, this is the output

*WM: Adding parameter
*WM: timeZone
*WM: Adding parameter
*WM: military
*WM: Adding parameter
*WM: metric
*WM: Adding parameter
*WM: date_fmt
No Double Reset Detected
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 192.168.137.103
WiFi connected, IP address: 192.168.137.103
timezone=
military=
metric=
date-format=
connecting to weather server.. connected.
weather:{"coord":{"lon":-1.88,"lat":50.72},"weather":[{"id":521,"main":"Rain","description":"shower rain","icon":"09d"}],"base":"stations","main":{"temp":72.66,"pressure":1006,"humidity":64,"temp_min":69.8,"temp_max":75.2},"visibility":10000,"wind":{"speed":5.82,"deg":200},"clouds":{"all":20},"dt":1533660600,"sys":{"type":1,"id":5081,"message":0.0096,"country":"GB","sunrise":1533617037,"sunset":1533670887},"id":2655095,"name":"Bournemouth","cod":200}
cond Rain
temp 72.66
press 1006
humi 64
*WM: freeing allocated params!
display color range [0 .. 65535]
day mode brightness
showing the weather
temperature: 72F
weather conditions 4
showing the date
Got NTP time: 17:24:07 07/08/2018
showing the weather
temperature: 72F
weather conditions 4
showing the date
showing the weather
temperature: 72F
weather conditions 4
connecting to weather server.. connected.
weather:{"coord":{"lon":-1.88,"lat":50.72},"weather":[{"id":521,"main":"Rain","description":"shower rain","icon":"09d"}],"base":"stations","main":{"temp":72.66,"pressure":1006,"humidity":64,"temp_min":69.8,"temp_max":75.2},"visibility":10000,"wind":{"speed":5.82,"deg":200},"clouds":{"all":20},"dt":1533660600,"sys":{"type":1,"id":5081,"message":0.0096,"country":"GB","sunrise":1533617037,"sunset":1533670887},"id":2655095,"name":"Bournemouth","cod":200}
cond Rain
temp 72.66
press 1006
humi 64
showing the weather
temperature: 72F
weather conditions 4
showing the weather
temperature: 72F
weather conditions 4

**Comment by lmirel** [comment]
> timezone=
military=
metric=
date-format=

this is not right. your flash data is either corrupted of cleaned but you don't have the right settings.
try going back to the AP mode (double reset) and reconfigure these to see if that helps.

**Comment by Joeboyc2** [comment]
I did see that, but wasnt sure where to set it, i dont get options like that in the web interface.

I will check again in a little bit

**Comment by lmirel** [comment]
this is what it should look like after configuration:
Should save config
timezone=0
military=Y
metric=Y
date-format=D.M.Y
WiFi connected, IP address: 192.168.2.123
Saving configuration to file:
timezone=0
military=Y
metric=Y
date-format=D.M.Y

**Comment by Joeboyc2** [comment]
Hey @lmirel ,

Reflashed and all now working fine:

Saving configuration to file:
timezone=+1
military=Y
metric=Y
date-format=D.M.Y
connecting to weather server.. connected.
