### ISSUE TITLE
Temp not displaying correctly

### ISSUE THREAD

**Issue by anthonyjclarke** [lmirel/MorphingClockRemix#5]
Seems a small issue with the display of the temp, looks like not clearing from when moves from multiple digits to one, attached a couple of examples
![image](https://user-images.githubusercontent.com/9491428/43863125-0cb06306-9b9f-11e8-8ebd-0898677d63aa.png)

**Comment by lmirel** [comment]
you might not have the latest code, can you do a pull and try again?

**Comment by anthonyjclarke** [comment]
Just updated, will leave to run and report back... interestingly had to do a few trys to get it to sync NTP clock as NTPlib was returning : 

Got NTP time: 08:00:37 01/01/1970
showing the weather
temperature: 5C
weather conditions 1
showing the date
Got NTP time: 08:00:47 01/01/1970
showing the weather
temperature: 5C
weather conditions 1
showing the date
Got NTP time: 07:51:01 10/08/2018
showing the weather

also had to do a reset to fix this display of the digit

![image](https://user-images.githubusercontent.com/9491428/43928026-caa90d58-9c72-11e8-9dab-086d94a28872.png)

**Comment by lmirel** [comment]
hmm.. weird. I saw the display artifact myself during development but I did a cleanup of the display after NTP sync such that it shouldn't have this issue.
it might be related to your NTP sync issue but can't tell exactly.
let me know if you see this again and report the circumstances if possible.
thanks and enjoy

**Comment by lmirel** [comment]
btw, I force NTP sync every 10sec until it gets the right time, that's why you see 'Got NTP time' every 10 sec.
after it gets the sync, I switch the sync to every hour or so.
