### ISSUE TITLE
error class NTPClient

### ISSUE THREAD

**Issue by UseAfterMe** [lmirel/MorphingClockRemix#6]
Needed to install Time-1.5.zip to even get this far or it would say missing time.h

MorphingClockRemix.ino: In function 'void loop()':
MorphingClockRemix:902: error: 'class NTPClient' has no member named 'getHour'
   hh = NTP.getHour ();
            ^
MorphingClockRemix:903: error: 'class NTPClient' has no member named 'getMinute'
   mm = NTP.getMinute ();
            ^
MorphingClockRemix:904: error: 'class NTPClient' has no member named 'getSecond'
   ss = NTP.getSecond ();
            ^
exit status 1
'class NTPClient' has no member named 'getHour'

**Comment by Joeboyc2** [comment]
To get past these errors you need to install these library's:
NTPClient by Fabrice Weinberg
Time by Michael Margolis
NtpClientLib by Germán Martín

**Comment by UseAfterMe** [comment]
Thanks I wound up reinstalling everything fresh and it worked, thank you.
One other issue is that the weather doesn't show. When checking the serial
console it connects to openweathermaps but says no weather data found. I
have tried about 20 locations and it's always the same.

**Comment by Joeboyc2** [comment]
the easyest way to fix that error is to remove the while loop that checks for the weather.

But having looked at the latest code it has been removed

Try using the latest version of the code, if it still fails,can you past the full output from the serial console

**Comment by bluem6** [comment]
evilsperm, 

I've the same error, how did you get it to clear? I've deleted the 3 libraries and reinstall them, still the same error...

**Comment by UseAfterMe** [comment]
@Joeboyc2 
I am using the latest src as of 2 days ago
Log:
WiFi connected, IP address: 10.0.0.88
timezone=-4
military=N
metric=N
date-format=M.D.Y
connecting to weather server.. connected.
*WM: freeing allocated params!
display color range [0 .. 65535]
day mode brightness
showing the weather
!no weather data available
showing the date
Got NTP time: 19:13:05 19/08/2018
showing the weather
!no weather data available
showing the date
weather:{"cod":"404","message":"city not found"}
temp NOT found!
pressure NOT found!
humidity NOT found!
Got NTP time: 19:10:31 19/08/2018
showing the weather
!no weather data available
showing the date
showing the weather
!no weather data available

took me a while to get the string weather:{"cod":"404","message":"city not found"}
I have tried the ID 5128581, and city in this format New York, US



@bluem6 
Make sure you clear out any ntp client you have in your arduino dir an use this one: 
https://github.com/2dom/NtpClient
If you have any others it will throw that error

**Comment by bluem6** [comment]
evilsperm, thank you very much.  I finally got the code to compile/upload.  For me to make it work do not install NtpClientLib.  Just the NtpClient an the Time libraries.  I do have another question and it seems like it's doing the same as with HariFun code where I can't see the MorphClk access point.  Does anyone know where in the code I need to edit if I need to manually input in my access point and password?

**Comment by wudave** [comment]
You may need to adjust the refresh rate.  Please see below link or use Hari's Experimental12E branch https://github.com/hwiguna/HariFun_166_Morphing_Clock/blob/Experimental12E/Latest/MorphingClock/MorphingClock.ino. 
https://github.com/lmirel/MorphingClockRemix/issues/4#issuecomment-412319465
Note that after you change refresh rate to connect WiFi and get credential, you may need to change it back if you see display flickering.  You only need to slow down the refresh during setup.

**Comment by UseAfterMe** [comment]
@bluem6
Good to know it worked out for you. As for the wifi if you installed the
original Hari clock make sure you set it to wipe everything  when compiling
and upload. Than double press the reset button with about 1 sec in-between
presses. It should show the AP on the matrix. After that you should be able
to connect and change what you need.

**Comment by lmirel** [comment]
@evilsperm thanks for the tip on version 1.5 for Time lib.
I actually imported the master branch at the time I wrote this and didn't have time to look back at this detail.

**Comment by lmirel** [comment]
> evilsperm, thank you very much. I finally got the code to compile/upload. For me to make it work do not install NtpClientLib. Just the NtpClient an the Time libraries. I do have another question and it seems like it's doing the same as with HariFun code where I can't see the MorphClk access point. Does anyone know where in the code I need to edit if I need to manually input in my access point and password?

if you don't need the whole WiFi manager for settings, look at the 'no-wm' branch. you can then setup all parameters in a params.h file.
